name: discussion_page_server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  hive: ^1.4.0+1
dev_dependencies:
  pedantic: ^1.8.0
  hive_generator: ^0.7.0
  build_runner: ^1.7.4